import type { PermissionId, RoleId, RolePermissionMap } from "@/types/rbac";
import type { SystemRoleDefinition } from "@/types/rbac";
import { PERMISSION_IDS, PLATFORM_PERMISSION_IDS } from "./catalog";

export const SYSTEM_ROLES: SystemRoleDefinition[] = [
  {
    id: "super_admin",
    name: "Super Admin",
    description: "Administración global de la plataforma SmartServe",
    rank: 100,
    scope: "platform",
    assignableOnSignup: false,
    createsVenue: false,
  },
  {
    id: "propietario",
    name: "Propietario",
    description: "Dueño del restaurante: billing, roles y operación total",
    rank: 90,
    scope: "tenant",
    assignableOnSignup: true,
    createsVenue: true,
  },
  {
    id: "gerente",
    name: "Gerente",
    description: "Operación completa excepto billing y permisos críticos",
    rank: 80,
    scope: "tenant",
    assignableOnSignup: false,
    createsVenue: false,
  },
  {
    id: "supervisor",
    name: "Supervisor",
    description: "Turno, sala e inventario operativo",
    rank: 70,
    scope: "tenant",
    assignableOnSignup: false,
    createsVenue: false,
  },
  {
    id: "cajero",
    name: "Cajero",
    description: "Cobros, caja y facturación de consumo",
    rank: 50,
    scope: "tenant",
    assignableOnSignup: false,
    createsVenue: false,
  },
  {
    id: "mesero",
    name: "Mesero",
    description: "Mesas y pedidos en sala",
    rank: 40,
    scope: "tenant",
    assignableOnSignup: false,
    createsVenue: false,
  },
  {
    id: "cocinero",
    name: "Cocinero",
    description: "Pantalla de cocina y estados de preparación",
    rank: 35,
    scope: "tenant",
    assignableOnSignup: false,
    createsVenue: false,
  },
  {
    id: "barista",
    name: "Barista",
    description: "Barra y bebidas",
    rank: 35,
    scope: "tenant",
    assignableOnSignup: false,
    createsVenue: false,
  },
  {
    id: "repartidor",
    name: "Repartidor",
    description: "Pedidos delivery y estados de entrega",
    rank: 30,
    scope: "tenant",
    assignableOnSignup: false,
    createsVenue: false,
  },
  {
    id: "cliente",
    name: "Cliente",
    description: "App de cliente: reservas propias, pedidos y fidelización",
    rank: 10,
    scope: "tenant",
    assignableOnSignup: true,
    createsVenue: false,
  },
];

function none(): RolePermissionMap {
  return Object.fromEntries(PERMISSION_IDS.map((id) => [id, false])) as RolePermissionMap;
}

function enable(map: RolePermissionMap, ids: PermissionId[]): RolePermissionMap {
  const next = { ...map };
  for (const id of ids) next[id] = true;
  return next;
}

const ALL_TENANT = PERMISSION_IDS.filter((id) => !PLATFORM_PERMISSION_IDS.includes(id));

/** Default boolean matrix per system role — every permission individually toggleable later via overlay. */
export const SYSTEM_ROLE_DEFAULTS: Record<RoleId, RolePermissionMap> = {
  super_admin: enable(none(), PERMISSION_IDS),

  propietario: enable(none(), ALL_TENANT),

  gerente: enable(none(), [
    "restaurant.read",
    "restaurant.update",
    "billing.read",
    "settings.read",
    "settings.manage",
    "branches.read",
    "branches.create",
    "branches.update",
    "members.read",
    "members.invite",
    "members.update",
    "roles.read",
    "roles.assign",
    "employees.read",
    "employees.manage",
    "employees.shifts.manage",
    "catalog.read",
    "catalog.products.manage",
    "catalog.categories.manage",
    "catalog.ingredients.manage",
    "inventory.read",
    "inventory.adjust",
    "inventory.purchases.manage",
    "inventory.waste.manage",
    "inventory.suppliers.manage",
    "tables.read",
    "tables.manage",
    "pos.access",
    "pos.discount",
    "pos.tip",
    "pos.split",
    "pos.move_merge",
    "orders.read",
    "orders.create",
    "orders.update",
    "orders.cancel",
    "orders.refund",
    "payments.charge",
    "payments.refund",
    "payments.cash_drawer",
    "invoices.read",
    "invoices.issue",
    "invoices.void",
    "kitchen.access",
    "kitchen.update_status",
    "bar.access",
    "bar.update_status",
    "delivery.access",
    "delivery.update_status",
    "delivery.assign",
    "customers.read",
    "customers.manage",
    "loyalty.read",
    "loyalty.adjust",
    "reservations.read",
    "reservations.manage",
    "marketing.read",
    "marketing.campaigns.manage",
    "marketing.coupons.manage",
    "reports.read",
    "history.read",
    "audit.read",
    "ai.assistant",
    "ai.insights",
    "ai.manage",
    "notifications.read",
    "notifications.manage",
    "website.read",
    "website.manage",
  ]),

  supervisor: enable(none(), [
    "restaurant.read",
    "settings.read",
    "branches.read",
    "members.read",
    "members.invite",
    "roles.read",
    "employees.read",
    "employees.shifts.manage",
    "catalog.read",
    "inventory.read",
    "inventory.adjust",
    "inventory.waste.manage",
    "tables.read",
    "tables.manage",
    "pos.access",
    "pos.discount",
    "pos.tip",
    "pos.split",
    "pos.move_merge",
    "orders.read",
    "orders.create",
    "orders.update",
    "orders.cancel",
    "payments.charge",
    "payments.cash_drawer",
    "invoices.read",
    "invoices.issue",
    "kitchen.access",
    "kitchen.update_status",
    "bar.access",
    "bar.update_status",
    "delivery.access",
    "delivery.update_status",
    "delivery.assign",
    "customers.read",
    "customers.manage",
    "loyalty.read",
    "reservations.read",
    "reservations.manage",
    "marketing.read",
    "reports.read",
    "history.read",
    "ai.assistant",
    "ai.insights",
    "notifications.read",
    "website.read",
    "website.manage",
  ]),

  cajero: enable(none(), [
    "restaurant.read",
    "branches.read",
    "catalog.read",
    "tables.read",
    "pos.access",
    "pos.discount",
    "pos.tip",
    "pos.split",
    "orders.read",
    "orders.create",
    "orders.update",
    "payments.charge",
    "payments.cash_drawer",
    "invoices.read",
    "invoices.issue",
    "customers.read",
    "customers.manage",
    "loyalty.read",
    "reservations.read",
    "notifications.read",
  ]),

  mesero: enable(none(), [
    "restaurant.read",
    "branches.read",
    "catalog.read",
    "tables.read",
    "pos.access",
    "pos.tip",
    "pos.split",
    "pos.move_merge",
    "orders.read",
    "orders.create",
    "orders.update",
    "customers.read",
    "customers.manage",
    "loyalty.read",
    "reservations.read",
    "reservations.manage",
    "notifications.read",
  ]),

  cocinero: enable(none(), [
    "restaurant.read",
    "branches.read",
    "catalog.read",
    "orders.read",
    "kitchen.access",
    "kitchen.update_status",
    "notifications.read",
  ]),

  barista: enable(none(), [
    "restaurant.read",
    "branches.read",
    "catalog.read",
    "orders.read",
    "bar.access",
    "bar.update_status",
    "notifications.read",
  ]),

  repartidor: enable(none(), [
    "restaurant.read",
    "branches.read",
    "orders.read",
    "delivery.access",
    "delivery.update_status",
    "customers.read",
    "notifications.read",
  ]),

  cliente: enable(none(), [
    "restaurant.read",
    "catalog.read",
    "orders.read",
    "orders.create",
    "reservations.read",
    "reservations.manage_own",
    "loyalty.read",
    "notifications.read",
  ]),
};

export function getSystemRole(roleId: RoleId): SystemRoleDefinition {
  const role = SYSTEM_ROLES.find((r) => r.id === roleId);
  if (!role) throw new Error(`Unknown role: ${roleId}`);
  return role;
}
